export const BUILTIN_9STEP_TEMPLATE = {
  id: 'builtin-9step',
  name: 'PRD -> PR delivery workflow',
  steps: [
    {
      seq: 1,
      name: 'Create workspace',
      ownerType: 'human',
      agentRole: null,
      preferredProvider: null,
      inputArtifactRoles: [],
      outputArtifactRoles: [],
      maxRetries: 0,
      retryBackoffSeconds: 0,
      dependsOnStepSeqs: [],
    },
    {
      seq: 2,
      name: 'Import PRD',
      ownerType: 'approval_gate',
      agentRole: null,
      preferredProvider: null,
      inputArtifactRoles: [],
      outputArtifactRoles: ['PRD'],
      maxRetries: 0,
      retryBackoffSeconds: 0,
      dependsOnStepSeqs: [1],
    },
    {
      seq: 3,
      name: 'Generate engineering plan',
      ownerType: 'agent',
      agentRole: 'planner',
      preferredProvider: 'anthropic',
      inputArtifactRoles: ['PRD'],
      outputArtifactRoles: ['PLAN'],
      maxRetries: 2,
      retryBackoffSeconds: 30,
      dependsOnStepSeqs: [2],
    },
    {
      seq: 4,
      name: 'Break plan into tasks',
      ownerType: 'agent',
      agentRole: 'tasker',
      preferredProvider: 'anthropic',
      inputArtifactRoles: ['PLAN'],
      outputArtifactRoles: ['TASK_LIST'],
      maxRetries: 2,
      retryBackoffSeconds: 30,
      dependsOnStepSeqs: [3],
    },
    {
      seq: 5,
      name: 'Agent implementation',
      ownerType: 'agent',
      agentRole: 'coder',
      preferredProvider: 'anthropic',
      inputArtifactRoles: ['TASK_LIST'],
      outputArtifactRoles: ['CODE_PATCH'],
      maxRetries: 1,
      retryBackoffSeconds: 60,
      dependsOnStepSeqs: [4],
    },
    {
      seq: 6,
      name: 'Run tests',
      ownerType: 'agent',
      agentRole: 'tester',
      preferredProvider: 'anthropic',
      inputArtifactRoles: ['CODE_PATCH'],
      outputArtifactRoles: ['TEST_REPORT'],
      maxRetries: 1,
      retryBackoffSeconds: 60,
      dependsOnStepSeqs: [5],
    },
    {
      seq: 7,
      name: 'Code review',
      ownerType: 'agent',
      agentRole: 'reviewer',
      preferredProvider: 'anthropic',
      inputArtifactRoles: ['CODE_PATCH', 'TEST_REPORT'],
      outputArtifactRoles: ['REVIEW_COMMENT'],
      maxRetries: 1,
      retryBackoffSeconds: 30,
      dependsOnStepSeqs: [6],
    },
    {
      seq: 8,
      name: 'Final human review',
      ownerType: 'approval_gate',
      agentRole: null,
      preferredProvider: null,
      inputArtifactRoles: ['REVIEW_COMMENT'],
      outputArtifactRoles: [],
      maxRetries: 0,
      retryBackoffSeconds: 0,
      dependsOnStepSeqs: [7],
    },
    {
      seq: 9,
      name: 'Generate PR summary',
      ownerType: 'agent',
      agentRole: 'summarizer',
      preferredProvider: 'anthropic',
      inputArtifactRoles: ['CODE_PATCH', 'TEST_REPORT', 'REVIEW_COMMENT'],
      outputArtifactRoles: ['PR_SUMMARY'],
      maxRetries: 1,
      retryBackoffSeconds: 30,
      dependsOnStepSeqs: [8],
    },
  ] as const,
};
