import { execFile } from 'node:child_process';
import { promisify } from 'node:util';

import type { workflowRuns } from '../db/schema/workflows.js';
import type { workspaces } from '../db/schema/workspaces.js';

const execFileAsync = promisify(execFile);

async function run(command: string, args: string[], cwd: string, timeout = 120000) {
  try {
    const { stdout, stderr } = await execFileAsync(command, args, { cwd, timeout });
    return `${stdout}${stderr}`.trim();
  } catch (error) {
    const err = error as Error & { stdout?: string; stderr?: string };
    throw new Error([err.message, err.stdout, err.stderr].filter(Boolean).join('\n').trim());
  }
}

function parseGitHubRepo(value: string) {
  const https = value.match(/^https:\/\/github\.com\/([^/\s]+)\/([^/\s]+?)(?:\.git)?\/?$/);
  if (https) return `${https[1]}/${https[2]}`;

  const ssh = value.match(/^git@github\.com:([^/\s]+)\/([^/\s]+?)(?:\.git)?$/);
  if (ssh) return `${ssh[1]}/${ssh[2]}`;

  throw new Error(`Unsupported GitHub repository URL: ${value}`);
}

async function repoRemoteUrl(repo: string, cwd: string) {
  const json = await run('gh', ['repo', 'view', repo, '--json', 'sshUrl,url'], cwd);
  const parsed = JSON.parse(json) as { sshUrl?: string; url?: string };
  return parsed.sshUrl || parsed.url || `https://github.com/${repo}.git`;
}

async function ensureGitHubRepo(repo: string, cwd: string) {
  try {
    return await repoRemoteUrl(repo, cwd);
  } catch {
    await run('gh', ['repo', 'create', repo, '--private'], cwd);
    return repoRemoteUrl(repo, cwd);
  }
}

async function setOrigin(remoteUrl: string, cwd: string) {
  try {
    await run('git', ['remote', 'get-url', 'origin'], cwd);
    await run('git', ['remote', 'set-url', 'origin', remoteUrl], cwd);
  } catch {
    await run('git', ['remote', 'add', 'origin', remoteUrl], cwd);
  }
}

async function ensureLocalBranch(branch: string, cwd: string) {
  try {
    await run('git', ['rev-parse', '--verify', `refs/heads/${branch}`], cwd);
    await run('git', ['checkout', branch], cwd);
  } catch {
    await run('git', ['checkout', '-B', branch], cwd);
  }
}

function prTitle(summary: string, workspaceName: string) {
  const lines = summary
    .split('\n')
    .map((line) => line.replace(/^#+\s*/, '').trim());
  const conventional = lines.find((line) => /^[a-z]+(?:\([^)]+\))?!?:\s+\S/.test(line));
  if (conventional) return conventional.slice(0, 120);

  const first = lines
    .find((line) => line &&
      !line.startsWith('Query:') &&
      !line.startsWith('You are ') &&
      !line.startsWith('Return ') &&
      !line.startsWith('Put ') &&
      !line.startsWith('Include ') &&
      !line.startsWith('Input artifacts') &&
      !line.startsWith('Provider:') &&
      !line.startsWith('Command:') &&
      !line.startsWith('Exit code:') &&
      !line.startsWith('Initializing agent') &&
      !line.startsWith('─') &&
      !line.startsWith('╭') &&
      !line.startsWith('╰') &&
      !line.startsWith('Resume this session') &&
      !line.startsWith('Session:') &&
      !line.startsWith('Duration:') &&
      !line.startsWith('Messages:'));
  return first?.slice(0, 120) || `AWW delivery: ${workspaceName}`;
}

export async function publishWorkspaceToGitHub(
  workspace: Pick<typeof workspaces.$inferSelect, 'name' | 'githubRepoUrl' | 'defaultBranch'>,
  runInfo: Pick<typeof workflowRuns.$inferSelect, 'featureBranch'>,
  codeDir: string,
  summary: string,
) {
  if (!workspace.githubRepoUrl) {
    throw new Error('Workspace has no GitHub repository URL configured.');
  }
  if (!runInfo.featureBranch) {
    throw new Error('Workflow run has no feature branch.');
  }

  const repo = parseGitHubRepo(workspace.githubRepoUrl);
  const remoteUrl = await ensureGitHubRepo(repo, codeDir);
  await setOrigin(remoteUrl, codeDir);

  const baseBranch = workspace.defaultBranch || 'main';
  await ensureLocalBranch(runInfo.featureBranch, codeDir);
  await run('git', ['push', '-u', 'origin', baseBranch], codeDir);
  await run('git', ['push', '-u', 'origin', runInfo.featureBranch], codeDir);

  try {
    const existing = await run(
      'gh',
      ['pr', 'view', runInfo.featureBranch, '--repo', repo, '--json', 'url', '--jq', '.url'],
      codeDir,
    );
    if (existing) return { repo, remoteUrl, prUrl: existing };
  } catch {
    // No existing PR for this branch.
  }

  const prUrl = await run(
    'gh',
    [
      'pr',
      'create',
      '--repo',
      repo,
      '--base',
      baseBranch,
      '--head',
      runInfo.featureBranch,
      '--title',
      prTitle(summary, workspace.name),
      '--body',
      summary || 'Generated by AWW.',
    ],
    codeDir,
  );

  return { repo, remoteUrl, prUrl };
}
